### ISSUE TITLE
bech32 encoding

### ISSUE THREAD

**Issue by lishuailibertine** [harmony-one/ledger-app-one#15]
Test code：
mnemonic: produce often swift tumble humor fat finish remove fire skull gossip globe
Get address with bech32 encoding: one1xqexywfnxfskvc3nxvurjdnxv3jx2etrxsmrwvfcxc6rgv3exfsn8n0kpfp;

But the correct generated address should be:
one1kx8f98avylkglwlns8rv5jp4yk09pwrnyhk98z;

Can you tell me why?

**Comment by coolcottontail** [comment]
Can you tell me how do you derive the address from mnemonic ? 
Ledger one app is using HD Wallet withbip32 path for ONE is 44'/1023'/0'/0/0  to derive the key.

**Comment by coolcottontail** [comment]
also why  your derived one address string is longer than normal one address one1xqexywfnxfskvc3nxvurjdnxv3jx2etrxsmrwvfcxc6rgv3exfsn8n0kpfp ?

**Comment by lishuailibertine** [comment]
> also why your derived one address string is longer than normal one address one1xqexywfnxfskvc3nxvurjdnxv3jx2etrxsmrwvfcxc6rgv3exfsn8n0kpfp ?


My private key is: 3cdb9ed21dedc0c454634f148685df05a6c5fb44bcbb4fda127705d8912498ee ;
My public key is 02b932afb33896fddeec46718644292a7cdcf8d65b8da88194c2a4b7f7f695e591;

```
bech32_get_address(&out, publicKeyData,publicKeyDataWithLength);
```
Does the input parameter of bech32_get_address need special treatment?

**Comment by coolcottontail** [comment]
bech32_get_address(...) the publicKeyData parameter requires the 20 byte ethererum address.  
the address you posted is 66 byte address....  you need to first convert your 66 byte address to 20 byte ETH address then call bech32_get_address(...) to get ONE address.

please check https://github.com/harmony-one/ledger-app-one/blob/master/src/harmony.c#L121 for reference

**Comment by lishuailibertine** [comment]
> bech32_get_address(...) the publicKeyData parameter requires the 20 byte ethererum address.
> the address you posted is 66 byte address.... you need to first convert your 66 byte address to 20 byte ETH address then call bech32_get_address(...) to get ONE address.
> 
> please check https://github.com/harmony-one/ledger-app-one/blob/master/src/harmony.c#L121 for reference


Ok, i will try it, thank you very much
